# Generated by Django 3.2.21 on 2023-09-25 21:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
