# Generated by Django 3.2.21 on 2023-09-27 17:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_rename_blogposts_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
